import RightHeader from '@/Components/RightHeader'
import Headers from '../Components/Headers'
import './globals.css'
import { Inter } from 'next/font/google'
import TopMiddleHeader from '@/Components/TopMiddleHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`flex h-[150vh] w-full`}>
        <div>
          <Headers />
        </div>
        <div className='flex flex-col bg-gray-100  flex-1 justify-start items-center'>
          <TopMiddleHeader/>
          {children}
        </div>
        <div>
          <RightHeader />
        </div>
      </body>
    </html>
  )
}
