import RightHeader from '@/Components/RightHeader'
import Headers from '../Components/Headers'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`flex`}>
        <div>
          <Headers />
        </div>
        {children}
        <div>
          <RightHeader />
        </div>
      </body>
    </html>
  )
}
